### ISSUE TITLE
Full name feature to use in the certificate

### ISSUE THREAD

**Issue by y2749zha** [open-archives-data-rescue/climate-data-rescue#266]
To use the certificate for CCR, we would want students to show their full names on the certificate instead of their displayed nicknames. We would also want to give students some freedom to use their nicknames while working on transcribing. So we want to keep the nickname feature while developing a new feature to collect and save their full name and show it on the certificate.

Currently, I'm thinking putting the full name entry on my profile page next to the nickname entry. So students and save and edit it easily together with their personal information.

**Comment by rsmithlal** [comment]
This is a good idea. I've been working on integrating the Better Together engine and using the `Person` model to store the full name. You can get a start on adding the HTML view changes while I am working to make the changes to the models.

You will need to add a `name` text field that we will use to collect the name for the person. It should appear in the sign up form and the edit form. It should also be used on the certificate.

You can add an `attr_acessor :name` to the user model to allow you to temporarily access that property on user and develop the views while I'm making the model changes.

When you have made changes that are OK and working, please commit them to a new branch and push the branch so we can create a pull request. Always pull production and branch off of the latest version of it when creating a new branch.

**Comment by VickyS08** [comment]
I agree with having a name added. Let me know when you have something to look at!

**Comment by raakal** [comment]
I think this sounds like a good idea too. It shouldn't disrupt the sign-up process and if it is something current users can add/change on their profile page that's great! 

Maybe we should put a hover text beside the field on the sign-up page stating that the real name will only be used on the generated certificate? As an extra insurance for individuals who could be concerned. We should also add this as an item to our terms and conditions, noting that we will not distribute their name, etc. etc.
