### ISSUE TITLE
Certificate Updates

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#291]
For the DRAW Participation Certificate:

Full name has not been translated on the French side of the Profile page on the website. It should be replaced with 'Nom complet'.

In addition, Edit has been translated to 'Éditer' and should instead be 'Modifier'.

See photo for example.

![Screen Shot 2020-09-27 at 2 50 45 PM](https://user-images.githubusercontent.com/46582468/94373038-92249280-00d0-11eb-8c9e-df10bb209d43.png)

**Comment by rsmithlal** [comment]
Hey Rachel! You can actually make these changes yourself if you're feeling up to it! You can edit files directly in this GitHub web interface. 

The translations are in the config folder in the en.yml and fr.yml files. You can search in the fr.yml file for the values and change them. You should choose to create a new branch when prompted while committing your changes. Pick a branch name with no spaces but you can use dashes between words. Keep it short but descriptive.

If the incorrect value is not found in fr.yml, look for the vue in en.yml and note the key and its place in the nested key hierarchy. Find that key in fr.yml and you will find the correct value to change. There may be multiple instances of a key name but they should be nested in a reasonable manner.

If you want, you can follow the instructions in the readme and you should be able to get the app running locally and make the changes directly on your development environment in a text editor like Sublime or Visual Studio. If you have questions, you can ask myself or Melis.

**Comment by raakal** [comment]
Hi Rob - I don't think I'm going to have a chance  to make these changes myself. I've have quite the workload at the moment in regards to content creation/management on the website, outreach, and prep/meetings. I'll see if I have a chance to review the instructions you have included so that I can do so next time, but for this instance I think Yumeng should do it.
