### ISSUE TITLE
Drop Down options for Certificate 

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#299]
The current participation certificate displays total completed transcriptions for all time for a user. 

It would be nice if a user could select a time frame (ie, from date 1 to date 2) to show case specific transcriptions completed during that frame of time.  This would particularly be useful for the Co-Curricular Record (CCR) at McGill where participants track their volunteer hours and submit them each semester.

This could function as a drop down menu perhaps, with a calendar to select date ranges (similar to how dates are selected in the transcription app).

**Comment by rsmithlal** [comment]
Hmm this is an interesting requirement! Could you maybe define more clearly what you mean by a completed transcription?

We don't presently store a date to track when the transcription was marked as complete. The best we could do right now is to use a combination of the date it was last updated and where the complete flag is set to true.

**Comment by raakal** [comment]
What I mean by completed transcription is less about full pages and more about data points entered. At the moment the certificate displays all transcribed data points (the data in the cells) since the user first started transcribing, whether a page is completed or not. Instead, we are suggesting parsing it by time. So if I want to see the transcriptions I've done for the month of November I would select Nov 1 to Nov 30 and it would display the transcriptions completed during that time, instead of all transcriptions. 

Does this help?

**Comment by rsmithlal** [comment]
Update from meeting last night:

In order for this work to be completed, we will need to add created_at and updated_at timestamps to the data_entries table. We will then have to set the values for those columns to be the same as their associated annotation so they have values that makes sense and are not just defaulted to the current date and time.

We will then add a filter mechanism to filter the user's data entries based on the start and end date that have been selected in the interface.

We can use the date time picker plugin (that we use for the transcriber box and metadata form) to have the user pick dates for the start and end date used for the filter.
