### ISSUE TITLE
Improvements to new pages data table

### ISSUE THREAD

**Issue by rsmithlal** [open-archives-data-rescue/climate-data-rescue#319]
New to-dos after review:
- [ ] Add paged and total records count to pagination zone
- [ ] Ensure that pages table refreshes results when the language is switched

Will copy over more from the other issue soon!

**Comment by raakal** [comment]
@rsmithlal From Jazmine: "Being able to filter the Admin Pages table by Transcriptions marked complete by the user, to be able to identify newly completed transcriptions and check them for completion. This would help to avoid pages sitting idle too long and being transcribed many times over while others are not yet done."
