### ISSUE TITLE
Save button doesn't work in the transcriber panel in Firefox

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#410]
The user describes that the save button for the transcriber panel does not work in Firefox although it does work in Chrome.

The user tried to reload the page and log out and back in but it did not make a difference. They also note that after inputting the transcriptions on Chrome, they did not appear in Firefox. 

https://user-images.githubusercontent.com/46582468/120856503-fe07a680-c54d-11eb-9a1a-92b890241b71.mp4

**Comment by balen** [comment]
this is no longer a bug
