### ISSUE TITLE
Date/Time reverts three hours back when filling in new fields

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#411]
The user reports that the date/time field changes 3 hours back automatically when filling in the other fields in the transcriber panel.

The user tried to reload the page to see if the issue reoccurred. The user tried browsers including Chrome, Firefox and Edge.

https://user-images.githubusercontent.com/46582468/120856921-7ff7cf80-c54e-11eb-9629-80b38027b4d7.mp4

**Comment by balen** [comment]
I am unable to replicate this problem. Is there more information, was the user's machine in a different timezone? @VickyS08
