### ISSUE TITLE
Account Confirmation Error

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#416]
Users are reporting that when they sign up for a DRAW account they encounter an error in being unable to change their password or confirm their email address and thus login to their account to begin transcribing. 

The error encounter is as follows:

"DNS_PROBE_FINISHED_NXDOMAIN" and “ERR_EMPTY_RESPONSE"

Users tried the following to trouble shoot:

- check FAQ
- reload page
- ask for another confirmation email to be sent
- check internet connection
- delete all my cookies
- open VPN
- close VPN
- reset CMD
- reset DNS

**Comment by rsmithlal** [comment]
This has now been resolved
